apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workloadidentityconfigs.test.com
spec:
  scope: Namespaced
  group: test.com
  names:
    kind: WorkloadIdentityConfig
    plural: workloadidentityconfigs
    singular: workloadidentityconfig
    shortNames:
      - wic
      - wics
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                projectId:
                  type: string
                gcpServiceAccountName:
                  type: string
                buckets:
                  type: array
                  items:
                    type: string
                k8sServiceAccountName:
                  type: string
                permissions:
                  type: array
                  items:
                    type: string
                bigquery:
                  type: object
                  properties:
                    datasets:
                      type: array
                      items:
                        type: string
                lifecycle:
                  type: object
                  properties:
                    reclaimPolicy:
                      type: string
